#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=conjiweb_env_lib.sh
source "${ROOT_DIR}/scripts/conjiweb_env_lib.sh"
ENV_FILE="${ENV_FILE:-${ROOT_DIR}/.env}"
EXAMPLE_FILE="${EXAMPLE_FILE:-${ROOT_DIR}/.env.example}"
ASSUME_YES=0
NONINTERACTIVE=0

usage() {
  cat <<'USAGE'
Usage: bash scripts/env_wizard.sh [--yes] [--non-interactive]

Creates or repairs .env before install:
  - prompts for DOMAIN and EMAIL when interactive
  - auto-generates DB/Redis/MinIO/SECRET/TURN/XMPP/admin secrets
  - optionally enables OIDC, LDAP, and external Prometheus CIDR
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --yes|-y) ASSUME_YES=1; shift ;;
    --non-interactive) NONINTERACTIVE=1; ASSUME_YES=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

if [[ ! -f "$ENV_FILE" ]]; then
  [[ -f "$EXAMPLE_FILE" ]] || { echo "Missing .env.example" >&2; exit 1; }
  cp "$EXAMPLE_FILE" "$ENV_FILE"
  chmod 600 "$ENV_FILE" || true
fi
sed -i 's/\r$//' "$ENV_FILE"

prompt_value() {
  local key="$1" label="$2" default="$3" validator="$4" value
  value="$(get_env_file_value "$ENV_FILE" "$key" "")"
  if [[ -n "$value" && "$value" != "chat.example.com" && "$value" != "you@example.com" ]]; then
    if [[ "$validator" == domain ]]; then
      valid_domain_name "$value" && return 0
    elif [[ "$validator" == email ]]; then
      valid_email "$value" && return 0
    else
      return 0
    fi
  fi
  if [[ "$NONINTERACTIVE" -eq 1 ]]; then
    value="$default"
  else
    while true; do
      read -r -p "$label [$default]: " value || true
      value="${value:-$default}"
      if [[ "$validator" == domain ]]; then
        valid_domain_name "$value" && break
        echo "Invalid domain. Use a bare hostname like chat.example.com, without https:// or path."
      elif [[ "$validator" == email ]]; then
        valid_email "$value" && break
        echo "Invalid email."
      else
        break
      fi
    done
  fi
  set_env_file_value "$ENV_FILE" "$key" "$value"
}

prompt_yes_no() {
  local label="$1" default="$2" ans
  if [[ "$ASSUME_YES" -eq 1 ]]; then
    [[ "$default" == "yes" ]] && return 0 || return 1
  fi
  read -r -p "$label [$default]: " ans || true
  ans="${ans:-$default}"
  case "$ans" in y|Y|yes|YES|true|1) return 0 ;; *) return 1 ;; esac
}

prompt_value DOMAIN "Public domain" "chat.example.com" domain
DOMAIN_VALUE="$(get_env_file_value "$ENV_FILE" DOMAIN "")"
set_env_file_value "$ENV_FILE" PUBLIC_DOMAIN "$(get_env_file_value "$ENV_FILE" PUBLIC_DOMAIN "$DOMAIN_VALUE")"
set_env_file_value "$ENV_FILE" XMPP_DOMAIN "$(get_env_file_value "$ENV_FILE" XMPP_DOMAIN "$DOMAIN_VALUE")"
set_env_file_value "$ENV_FILE" FRONTEND_URL "https://${DOMAIN_VALUE}"
set_env_file_value "$ENV_FILE" OIDC_REDIRECT_URI "https://${DOMAIN_VALUE}/sso/oidc/callback"
set_env_file_value "$ENV_FILE" VAPID_EMAIL "admin@${DOMAIN_VALUE}"
prompt_value EMAIL "Let's Encrypt email" "admin@${DOMAIN_VALUE}" email

# Always generate missing secrets. Existing values are preserved.
[[ -n "$(get_env_file_value "$ENV_FILE" DB_PASS "")" ]] || set_env_file_value "$ENV_FILE" DB_PASS "$(random_hex 24)"
[[ -n "$(get_env_file_value "$ENV_FILE" POSTGRES_PASSWORD "")" ]] || set_env_file_value "$ENV_FILE" POSTGRES_PASSWORD "$(get_env_file_value "$ENV_FILE" DB_PASS "")"
[[ -n "$(get_env_file_value "$ENV_FILE" REDIS_PASS "")" ]] || set_env_file_value "$ENV_FILE" REDIS_PASS "$(random_hex 24)"
[[ -n "$(get_env_file_value "$ENV_FILE" SECRET_KEY "")" ]] || set_env_file_value "$ENV_FILE" SECRET_KEY "$(random_hex 32)"
[[ -n "$(get_env_file_value "$ENV_FILE" XMPP_ADMIN_PASS "")" ]] || set_env_file_value "$ENV_FILE" XMPP_ADMIN_PASS "$(random_urlsafe 24)"
[[ -n "$(get_env_file_value "$ENV_FILE" TURN_SECRET "")" ]] || set_env_file_value "$ENV_FILE" TURN_SECRET "$(random_hex 32)"
[[ -n "$(get_env_file_value "$ENV_FILE" MINIO_ROOT_PASSWORD "")" ]] || set_env_file_value "$ENV_FILE" MINIO_ROOT_PASSWORD "$(random_urlsafe 24)"

if [[ -z "$(get_env_file_value "$ENV_FILE" ADMIN_PASS_HASH "")" && -z "$(get_env_file_value "$ENV_FILE" ADMIN_PASS "")" ]]; then
  ADMIN_PASS_GENERATED="$(random_urlsafe 18)"
  set_env_file_value "$ENV_FILE" ADMIN_PASS "$ADMIN_PASS_GENERATED"
  cat > "${ROOT_DIR}/.admin-password.once" <<EOF2
Conjiweb temporary admin password generated by env_wizard.sh
ADMIN_USER=$(get_env_file_value "$ENV_FILE" ADMIN_USER "admin")
ADMIN_PASS=${ADMIN_PASS_GENERATED}
Copy this now. install.sh will hash it and remove plaintext ADMIN_PASS from .env.
EOF2
  chmod 600 "${ROOT_DIR}/.admin-password.once" || true
fi

if prompt_yes_no "Enable OIDC SSO" "no"; then
  set_env_file_value "$ENV_FILE" OIDC_ENABLED true
  if [[ "$NONINTERACTIVE" -ne 1 ]]; then
    read -r -p "OIDC issuer URL: " v; set_env_file_value "$ENV_FILE" OIDC_ISSUER "$v"
    read -r -p "OIDC client ID: " v; set_env_file_value "$ENV_FILE" OIDC_CLIENT_ID "$v"
    read -r -s -p "OIDC client secret: " v; echo; set_env_file_value "$ENV_FILE" OIDC_CLIENT_SECRET "$v"
  fi
else
  set_env_file_value "$ENV_FILE" OIDC_ENABLED false
fi

if prompt_yes_no "Enable LDAP login" "no"; then
  set_env_file_value "$ENV_FILE" LDAP_ENABLED true
  if [[ "$NONINTERACTIVE" -ne 1 ]]; then
    read -r -p "LDAP URL/server (ldap://...): " v; set_env_file_value "$ENV_FILE" LDAP_SERVER "$v"; set_env_file_value "$ENV_FILE" LDAP_URL "$v"
    read -r -p "LDAP bind DN template: " v; set_env_file_value "$ENV_FILE" LDAP_BIND_DN_TEMPLATE "$v"
    read -r -p "LDAP user base DN: " v; set_env_file_value "$ENV_FILE" LDAP_USER_BASE "$v"
  fi
else
  set_env_file_value "$ENV_FILE" LDAP_ENABLED false
fi

if prompt_yes_no "Prometheus will scrape from a public/external IP" "no"; then
  if [[ "$NONINTERACTIVE" -ne 1 ]]; then
    read -r -p "Prometheus allow CIDR/IP (example: 203.0.113.10/32): " v
    set_env_file_value "$ENV_FILE" PROMETHEUS_ALLOW_CIDR "$v"
  fi
fi

chmod 600 "$ENV_FILE" || true
bash "${ROOT_DIR}/scripts/env_validate.sh" --strict --env "$ENV_FILE"
echo "[OK] .env is ready: $ENV_FILE"
if [[ -f "${ROOT_DIR}/.admin-password.once" ]]; then
  echo "[INFO] Temporary admin password saved once in .admin-password.once. Copy it before install removes plaintext from .env."
fi
