#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=conjiweb_env_lib.sh
source "${ROOT_DIR}/scripts/conjiweb_env_lib.sh"
ENV_FILE="${ROOT_DIR}/.env"
STRICT=0
WARN_ONLY=0

usage() {
  cat <<'USAGE'
Usage: bash scripts/env_validate.sh [--env .env] [--strict] [--warn-only]

Validates Conjiweb .env before install or deploy.
--strict requires generated secrets to be present and strong enough.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env) ENV_FILE="$2"; shift 2 ;;
    --strict) STRICT=1; shift ;;
    --warn-only) WARN_ONLY=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

errors=0; warnings=0
fail() { echo "[ERR] $*" >&2; errors=$((errors+1)); }
warn() { echo "[WARN] $*" >&2; warnings=$((warnings+1)); }
require_len() {
  local key="$1" min="$2" value
  value="$(get_env_file_value "$ENV_FILE" "$key" "")"
  if [[ -z "$value" ]]; then
    if [[ "$STRICT" -eq 1 ]]; then fail "$key is empty; run scripts/env_wizard.sh to auto-generate it"; else warn "$key is empty and will be generated by install.sh"; fi
    return
  fi
  (( ${#value} >= min )) || fail "$key is too short; require at least ${min} characters"
}

[[ -f "$ENV_FILE" ]] || fail ".env not found: $ENV_FILE"
if [[ -f "$ENV_FILE" ]]; then
  DOMAIN="$(get_env_file_value "$ENV_FILE" DOMAIN "")"
  EMAIL="$(get_env_file_value "$ENV_FILE" EMAIL "")"
  valid_domain_name "$DOMAIN" || fail "DOMAIN must be a bare real hostname, without https://, path, or placeholder. Current: '${DOMAIN:-empty}'"
  valid_email "$EMAIL" || fail "EMAIL is empty or invalid. Current: '${EMAIL:-empty}'"

  require_len SECRET_KEY 32
  DB_PASS="$(get_env_file_value "$ENV_FILE" DB_PASS "")"
  PG_PASS="$(get_env_file_value "$ENV_FILE" POSTGRES_PASSWORD "")"
  if [[ -z "$DB_PASS" && -z "$PG_PASS" ]]; then
    if [[ "$STRICT" -eq 1 ]]; then fail "DB_PASS/POSTGRES_PASSWORD is empty"; else warn "DB_PASS is empty and will be generated by install.sh"; fi
  elif [[ -n "$DB_PASS" && ${#DB_PASS} -lt 16 ]]; then
    fail "DB_PASS is too short; require at least 16 characters"
  elif [[ -n "$PG_PASS" && ${#PG_PASS} -lt 16 ]]; then
    fail "POSTGRES_PASSWORD is too short; require at least 16 characters"
  fi
  require_len MINIO_ROOT_PASSWORD 16
  require_len TURN_SECRET 32

  if is_truthy "$(get_env_file_value "$ENV_FILE" OIDC_ENABLED false)"; then
    [[ -n "$(get_env_file_value "$ENV_FILE" OIDC_ISSUER "")" ]] || fail "OIDC_ENABLED=true but OIDC_ISSUER is empty"
    [[ -n "$(get_env_file_value "$ENV_FILE" OIDC_CLIENT_ID "")" ]] || fail "OIDC_ENABLED=true but OIDC_CLIENT_ID is empty"
    [[ -n "$(get_env_file_value "$ENV_FILE" OIDC_CLIENT_SECRET "")" ]] || warn "OIDC_ENABLED=true but OIDC_CLIENT_SECRET is empty; only valid for public clients"
  fi
  if is_truthy "$(get_env_file_value "$ENV_FILE" LDAP_ENABLED false)"; then
    LDAP_URL="$(get_env_file_value "$ENV_FILE" LDAP_URL "")"
    LDAP_SERVER="$(get_env_file_value "$ENV_FILE" LDAP_SERVER "")"
    [[ -n "$LDAP_URL" || -n "$LDAP_SERVER" ]] || fail "LDAP_ENABLED=true but LDAP_URL/LDAP_SERVER is empty"
    [[ -n "$(get_env_file_value "$ENV_FILE" LDAP_BIND_DN_TEMPLATE "")" ]] || fail "LDAP_ENABLED=true but LDAP_BIND_DN_TEMPLATE is empty"
    [[ -n "$(get_env_file_value "$ENV_FILE" LDAP_USER_BASE "")" ]] || fail "LDAP_ENABLED=true but LDAP_USER_BASE is empty"
  fi

  if is_truthy "$(get_env_file_value "$ENV_FILE" METRICS_ENABLED true)"; then
    NGINX_FILE="${ROOT_DIR}/configs/nginx/conjiweb.conf"
    if [[ ! -f "$NGINX_FILE" ]]; then
      warn "METRICS_ENABLED=true but nginx config template not found"
    elif ! grep -q "location = /api/metrics" "$NGINX_FILE"; then
      fail "METRICS_ENABLED=true but nginx config has no /api/metrics location"
    elif ! grep -Eq "allow[[:space:]]+(127\.0\.0\.1|10\.0\.0\.0/8|172\.16\.0\.0/12|192\.168\.0\.0/16)" "$NGINX_FILE"; then
      fail "METRICS_ENABLED=true but nginx metrics endpoint has no allowed Prometheus/private CIDR"
    fi
  fi
fi

if [[ "$errors" -gt 0 ]]; then
  echo "[FAIL] env validation failed: ${errors} error(s), ${warnings} warning(s)" >&2
  [[ "$WARN_ONLY" -eq 1 ]] && exit 0 || exit 1
fi
echo "[OK] env validation passed (${warnings} warning(s))"
